export const Patois = [
    "Mi mout a mi market. ",
    "Weh no kill, fatten. ",
    "Yuh too fenkay, fenkay. ",
    "When Eskimo have money him buy fridge. ",
    "Never si come si. ",
    "Every poppy show have them owna gang. ",
    "A no all who go a church go fi prayah. ",
    "Nuh trouble trouble, until trouble trouble yuh. ",
    "Fowl eat an wipe him mouth a ground. ",
    "Same bird weh carry news come, a di same bird tek i back. ",
    "Di eyes a di master fatten di calf. ",
    "If yu cuss John crow peel head guinea hen vex. ",
    "Yuh cyaa tan pan cow back an cut cow tail. ",
    "Wen trouble tek yuh pickney shut fit yuh. ",
    "Tek kin teet kiba heart bun. ",
    "What a gwaan? ",
    "Weh yuh a seh? ",
    "Walk good. ",
    "Likkle more. ",
    "Ants follow fat, fat drown im. ",
    "Anansi rope tie him maasa. ",
    "All mout nuh set fi tell di same lie. ",
    "Pick an pick until yuh pick shit. ",
    "Poun a fret cyaa pay ounce a debt. ",
    "Teef neva love fi si teef wid long bag. ",
    "Good friend betta dan pocket money. ",
    "Haad ears pickny nyam rockstone. ",
    "Duppy know who fi frighten. ",
    "Fyah deh a mus-mus tail, him tink a cool breeze. ",
    "Every mickle mek a muckle. ",
    "Sorry fi mawga daag dem tun roun bite you. ",
    "Lawd tek di case an gi mi di pilla. ",
    "Ah wah duh dem? ",
    "Kunk. ",
    "Out a road. ",
    "Tings a gwaan. ",
    "Small up yuhself. ",
    "Lick shot. ",
    "Booyaka!",
    "Link mi. ",
    "Too nuff. ",
    "Kiba yuh mout. ",
    "Falla fashin monkey. ",
    "Broughtupsy. ",
    "If crab nuh walk im nuh fat but if im walk too much im en up inna carry pot. ",
    "Small axe fall big tree. ",
    "Cow neva know di use ah im tail til it cut off. ",
    "Fly ketch im pokey. "
];
